# Generated by Django 5.1.4 on 2025-06-24 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actores',
            fields=[
                ('actorid', models.AutoField(db_column='ActorID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=255)),
                ('fechanacimiento', models.DateField(blank=True, db_column='FechaNacimiento', null=True)),
                ('biografia', models.TextField(blank=True, db_column='Biografia', null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='actores/')),
            ],
            options={
                'db_table': 'actores',
            },
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('peliculaid', models.AutoField(db_column='PeliculaID', primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='Titulo', max_length=255)),
                ('titulooriginal', models.CharField(blank=True, db_column='TituloOriginal', max_length=255, null=True)),
                ('aniolanzamiento', models.IntegerField(blank=True, db_column='AnioLanzamiento', null=True)),
                ('director', models.CharField(blank=True, db_column='Director', max_length=255, null=True)),
                ('guionista', models.CharField(blank=True, db_column='Guionista', max_length=255, null=True)),
                ('genero', models.CharField(blank=True, db_column='Genero', max_length=100, null=True)),
                ('sinopsis', models.TextField(blank=True, db_column='Sinopsis', null=True)),
                ('clasificacion', models.CharField(blank=True, db_column='Clasificacion', max_length=10, null=True)),
                ('duracionminutos', models.IntegerField(blank=True, db_column='DuracionMinutos', null=True)),
                ('idiomaoriginal', models.CharField(blank=True, db_column='IdiomaOriginal', max_length=50, null=True)),
                ('paisproduccion', models.CharField(blank=True, db_column='PaisProduccion', max_length=100, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, db_column='FechaRegistro', null=True)),
            ],
            options={
                'db_table': 'peliculas',
            },
        ),
        migrations.CreateModel(
            name='Premios',
            fields=[
                ('premioid', models.AutoField(db_column='PremioID', primary_key=True, serialize=False)),
                ('nombrepremio', models.CharField(db_column='NombrePremio', max_length=255)),
                ('anioceremonia', models.IntegerField(blank=True, db_column='AnioCeremonia', null=True)),
                ('categoria', models.CharField(blank=True, db_column='Categoria', max_length=255, null=True)),
            ],
            options={
                'db_table': 'premios',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usuarioid', models.AutoField(db_column='UsuarioID', primary_key=True, serialize=False)),
                ('nombreusuario', models.CharField(db_column='NombreUsuario', max_length=50, unique=True)),
                ('correoelectronico', models.CharField(blank=True, db_column='CorreoElectronico', max_length=100, null=True, unique=True)),
                ('fecharegistro', models.DateTimeField(blank=True, db_column='FechaRegistro', null=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Peliculasactores',
            fields=[
                ('peliculaactorid', models.AutoField(db_column='PeliculaActorID', primary_key=True, serialize=False)),
                ('personaje', models.CharField(blank=True, db_column='Personaje', max_length=255, null=True)),
                ('actorid', models.ForeignKey(blank=True, db_column='ActorID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.actores')),
                ('peliculaid', models.ForeignKey(blank=True, db_column='PeliculaID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.peliculas')),
            ],
            options={
                'db_table': 'peliculasactores',
            },
        ),
        migrations.CreateModel(
            name='Peliculaspremios',
            fields=[
                ('peliculapremioid', models.AutoField(db_column='PeliculaPremioID', primary_key=True, serialize=False)),
                ('ganador', models.IntegerField(blank=True, db_column='Ganador', null=True)),
                ('peliculaid', models.ForeignKey(blank=True, db_column='PeliculaID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.peliculas')),
                ('premioid', models.ForeignKey(blank=True, db_column='PremioID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.premios')),
            ],
            options={
                'db_table': 'peliculaspremios',
            },
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('produccionid', models.AutoField(db_column='ProduccionID', primary_key=True, serialize=False)),
                ('productora', models.CharField(blank=True, db_column='Productora', max_length=255, null=True)),
                ('distribuidora', models.CharField(blank=True, db_column='Distribuidora', max_length=255, null=True)),
                ('presupuesto', models.DecimalField(blank=True, db_column='Presupuesto', decimal_places=2, max_digits=15, null=True)),
                ('recaudacion', models.DecimalField(blank=True, db_column='Recaudacion', decimal_places=2, max_digits=15, null=True)),
                ('peliculaid', models.ForeignKey(blank=True, db_column='PeliculaID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.peliculas')),
            ],
            options={
                'db_table': 'produccion',
            },
        ),
        migrations.CreateModel(
            name='Resenasusuarios',
            fields=[
                ('resenaid', models.AutoField(db_column='ResenaID', primary_key=True, serialize=False)),
                ('calificacion', models.DecimalField(blank=True, db_column='Calificacion', decimal_places=1, max_digits=2, null=True)),
                ('comentario', models.TextField(blank=True, db_column='Comentario', null=True)),
                ('fecharesena', models.DateTimeField(blank=True, db_column='FechaResena', null=True)),
                ('peliculaid', models.ForeignKey(blank=True, db_column='PeliculaID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.peliculas')),
                ('usuarioid', models.ForeignKey(blank=True, db_column='UsuarioID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.usuarios')),
            ],
            options={
                'db_table': 'resenasusuarios',
            },
        ),
    ]
